#!/usr/bin/env python3
"""
Environment Setup Script
Helps set up all required environment variables for the AI Career Advisor project
"""

import os
import sys
from pathlib import Path

def print_status(message, status="INFO"):
    """Print colored status messages"""
    colors = {
        "SUCCESS": "\033[92m",  # Green
        "ERROR": "\033[91m",    # Red
        "WARNING": "\033[93m",  # Yellow
        "INFO": "\033[94m",     # Blue
        "RESET": "\033[0m"      # Reset
    }
    
    color = colors.get(status, colors["INFO"])
    print(f"{color}[{status}]{colors['RESET']} {message}")

def create_backend_env():
    """Create or update backend .env file"""
    print_status("Setting up backend environment variables...", "INFO")
    
    env_file = Path("backend/.env")
    
    # Read existing .env if it exists
    existing_vars = {}
    if env_file.exists():
        try:
            with open(env_file, 'r') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#') and '=' in line:
                        key, value = line.split('=', 1)
                        existing_vars[key] = value
        except Exception as e:
            print_status(f"Warning: Could not read existing .env file: {str(e)}", "WARNING")
    
    # Get user input for missing variables
    required_vars = {
        "GEMINI_API_KEY": {
            "description": "Google Gemini AI API Key",
            "instructions": "Get your key from: https://makersuite.google.com/app/apikey",
            "current": existing_vars.get("GEMINI_API_KEY", "")
        },
        "FIREBASE_STORAGE_BUCKET": {
            "description": "Firebase Storage Bucket",
            "instructions": "Format: your-project-id.appspot.com",
            "current": existing_vars.get("FIREBASE_STORAGE_BUCKET", "")
        },
        "PORT": {
            "description": "Backend Port",
            "instructions": "Default: 5000",
            "current": existing_vars.get("PORT", "5000")
        }
    }
    
    optional_vars = {
        "SWE1_KEY": {
            "description": "Windsurf API Key (Optional)",
            "instructions": "Only if using Windsurf features",
            "current": existing_vars.get("SWE1_KEY", "")
        },
        "NODE_ENV": {
            "description": "Node Environment",
            "instructions": "development or production",
            "current": existing_vars.get("NODE_ENV", "development")
        }
    }
    
    new_vars = {}
    
    print("\n--- Required Environment Variables ---")
    for var_name, config in required_vars.items():
        print(f"\n{config['description']}")
        print(f"Instructions: {config['instructions']}")
        
        if config['current'] and not config['current'].startswith('your_'):
            print(f"Current value: {config['current']}")
            use_current = input("Use current value? (y/n): ").lower().strip()
            if use_current == 'y':
                new_vars[var_name] = config['current']
                continue
        
        new_value = input(f"Enter {var_name}: ").strip()
        while not new_value:
            print(f"{var_name} is required!")
            new_value = input(f"Enter {var_name}: ").strip()
        new_vars[var_name] = new_value
    
    print("\n--- Optional Environment Variables ---")
    for var_name, config in optional_vars.items():
        print(f"\n{config['description']}")
        print(f"Instructions: {config['instructions']}")
        
        if config['current'] and not config['current'].startswith('your_'):
            print(f"Current value: {config['current']}")
            use_current = input("Use current value? (y/n): ").lower().strip()
            if use_current == 'y':
                new_vars[var_name] = config['current']
                continue
        
        new_value = input(f"Enter {var_name} (press Enter to skip): ").strip()
        if new_value:
            new_vars[var_name] = new_value
    
    # Write .env file
    try:
        with open(env_file, 'w') as f:
            f.write("# AI Career Advisor - Backend Environment Variables\n")
            f.write("# Generated by setup_environment.py\n")
            f.write("# DO NOT commit this file to version control!\n\n")
            
            for var_name, value in new_vars.items():
                f.write(f"{var_name}={value}\n")
        
        print_status(f"✓ Backend .env file created/updated: {env_file}", "SUCCESS")
        return True
        
    except Exception as e:
        print_status(f"✗ Error creating backend .env file: {str(e)}", "ERROR")
        return False

def create_frontend_env():
    """Create or update frontend .env.local file"""
    print_status("\nSetting up frontend environment variables...", "INFO")
    
    env_file = Path("frontend/.env.local")
    
    # Read existing .env.local if it exists
    existing_vars = {}
    if env_file.exists():
        try:
            with open(env_file, 'r') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#') and '=' in line:
                        key, value = line.split('=', 1)
                        existing_vars[key] = value
        except Exception as e:
            print_status(f"Warning: Could not read existing .env.local file: {str(e)}", "WARNING")
    
    # Get user input for frontend variables
    frontend_vars = {
        "NEXT_PUBLIC_API_URL": {
            "description": "Backend API URL",
            "instructions": "For local development: http://localhost:5000",
            "current": existing_vars.get("NEXT_PUBLIC_API_URL", "http://localhost:5000")
        },
        "NEXT_PUBLIC_SITE_URL": {
            "description": "Frontend Site URL",
            "instructions": "For local development: http://localhost:3000",
            "current": existing_vars.get("NEXT_PUBLIC_SITE_URL", "http://localhost:3000")
        }
    }
    
    new_vars = {}
    
    print("\n--- Frontend Environment Variables ---")
    for var_name, config in frontend_vars.items():
        print(f"\n{config['description']}")
        print(f"Instructions: {config['instructions']}")
        print(f"Current value: {config['current']}")
        
        use_current = input("Use current value? (y/n): ").lower().strip()
        if use_current == 'y':
            new_vars[var_name] = config['current']
        else:
            new_value = input(f"Enter {var_name}: ").strip()
            while not new_value:
                print(f"{var_name} is required!")
                new_value = input(f"Enter {var_name}: ").strip()
            new_vars[var_name] = new_value
    
    # Write .env.local file
    try:
        with open(env_file, 'w') as f:
            f.write("# AI Career Advisor - Frontend Environment Variables\n")
            f.write("# Generated by setup_environment.py\n")
            f.write("# DO NOT commit this file to version control!\n\n")
            
            for var_name, value in new_vars.items():
                f.write(f"{var_name}={value}\n")
        
        print_status(f"✓ Frontend .env.local file created/updated: {env_file}", "SUCCESS")
        return True
        
    except Exception as e:
        print_status(f"✗ Error creating frontend .env.local file: {str(e)}", "ERROR")
        return False

def check_firebase_config():
    """Check Firebase configuration"""
    print_status("\nChecking Firebase configuration...", "INFO")
    
    service_account_path = Path("backend/src/config/serviceAccountKey.json")
    
    if service_account_path.exists():
        print_status("✓ Firebase service account key file exists", "SUCCESS")
        
        try:
            import json
            with open(service_account_path, 'r') as f:
                config = json.load(f)
            
            print(f"Project ID: {config.get('project_id', 'Not found')}")
            print(f"Client Email: {config.get('client_email', 'Not found')}")
            
            return True
        except Exception as e:
            print_status(f"✗ Error reading Firebase config: {str(e)}", "ERROR")
            return False
    else:
        print_status("⚠ Firebase service account key file not found", "WARNING")
        print("To set up Firebase:")
        print("1. Go to https://console.firebase.google.com/")
        print("2. Create a new project or select existing one")
        print("3. Go to Project Settings > Service Accounts")
        print("4. Click 'Generate new private key'")
        print("5. Save the JSON file as: backend/src/config/serviceAccountKey.json")
        return False

def main():
    """Main setup function"""
    print("=" * 60)
    print("🔧 AI Career Advisor - Environment Setup")
    print("=" * 60)
    
    # Change to project directory
    script_dir = Path(__file__).parent
    os.chdir(script_dir)
    
    success = True
    
    # Setup backend environment
    if not create_backend_env():
        success = False
    
    # Setup frontend environment
    if not create_frontend_env():
        success = False
    
    # Check Firebase configuration
    check_firebase_config()
    
    print("\n" + "=" * 60)
    print("📋 SETUP COMPLETE")
    print("=" * 60)
    
    if success:
        print_status("✓ Environment setup completed successfully!", "SUCCESS")
        print("\nNext steps:")
        print("1. Run 'python test_api_connectivity.py' to verify configuration")
        print("2. Start the backend servers")
        print("3. Start the frontend development server")
    else:
        print_status("✗ Some setup steps failed. Please check the errors above.", "ERROR")
        sys.exit(1)

if __name__ == "__main__":
    main()
