"""Provider abstraction, Gemini adapter, and deterministic test provider."""

import json
import os
from typing import Any, Protocol, runtime_checkable

import requests

from config.ai_config import AIProviderConfig, load_ai_config

from .contracts import AIRequest, AIResponse, AIResponseStatus


class AIProviderError(RuntimeError):
    code = "provider_error"
    retryable = False


class AIProviderUnavailable(AIProviderError):
    code = "provider_unavailable"


class AIProviderTimeout(AIProviderError):
    code = "provider_timeout"
    retryable = True


class AIProviderRateLimited(AIProviderError):
    code = "provider_rate_limited"
    retryable = True


class AIProviderInvalidResponse(AIProviderError):
    code = "provider_invalid_response"


class AIProviderConfigurationError(AIProviderError):
    code = "provider_configuration_error"


@runtime_checkable
class AIProvider(Protocol):
    """Provider contract used by the orchestrator and service layer."""

    def generate(self, request: AIRequest) -> AIResponse:
        raise NotImplementedError

    def provider_name(self) -> str:
        raise NotImplementedError

    def model_name(self) -> str:
        raise NotImplementedError


class NullAIProvider:
    """Provider used when AI is disabled or no safe provider is configured."""

    def provider_name(self) -> str:
        return "null"

    def model_name(self) -> str:
        return "disabled"

    def generate(self, request: AIRequest) -> AIResponse:
        return AIResponse(
            status=AIResponseStatus.UNAVAILABLE,
            summary="AI enrichment is not enabled.",
            confidence_notes=["No configured provider is available for this request."],
            refusal_or_abstention_reason="No external AI provider is configured.",
        )


class MockAIProvider:
    """Deterministic provider for tests and local UI verification."""

    def __init__(self, model: str = "mock-phase3c"):
        self._model = model

    def provider_name(self) -> str:
        return "mock"

    def model_name(self) -> str:
        return self._model

    def generate(self, request: AIRequest) -> AIResponse:
        evidence_ids = [item.evidence_id for item in request.context.evidence_registry]
        knowledge_ids = [item.knowledge_id for item in request.context.retrieved_knowledge]
        if not evidence_ids and not knowledge_ids:
            return AIResponse(
                status=AIResponseStatus.ABSTAINED,
                summary="",
                confidence_notes=["The deterministic context contains no explainable evidence."],
                refusal_or_abstention_reason="Insufficient grounded evidence for AI enrichment.",
            )

        first_evidence = evidence_ids[:1]
        first_knowledge = knowledge_ids[:1]
        return AIResponse(
            status=AIResponseStatus.COMPLETE,
            summary="This guidance is grounded in the verified deterministic context.",
            strengths=[
                {
                    "text": "The response is anchored to registered resume or job evidence.",
                    "evidence_reference_ids": first_evidence,
                }
            ] if first_evidence else [],
            learning_actions=[
                {
                    "text": f"Review {request.context.retrieved_knowledge[0].title} as general domain guidance.",
                    "knowledge_reference_ids": first_knowledge,
                }
            ] if first_knowledge else [],
            evidence_references=first_evidence,
            knowledge_references=first_knowledge,
            confidence_notes=["Generated by the deterministic mock provider."],
        )


class GeminiProvider:
    """Minimal Gemini REST adapter using server-side environment credentials."""

    def __init__(self, config: AIProviderConfig):
        self.config = config

    def provider_name(self) -> str:
        return "gemini"

    def model_name(self) -> str:
        return self.config.model_name

    def generate(self, request: AIRequest) -> AIResponse:
        api_key = os.getenv(self.config.api_key_env_var, "").strip()
        if not api_key:
            raise AIProviderConfigurationError("Configured AI provider credentials are unavailable.")

        payload = {
            "system_instruction": {
                "parts": [{"text": request.prompt.system_policy}],
            },
            "contents": [
                {
                    "role": "user",
                    "parts": [{"text": self._render_prompt(request)}],
                }
            ],
            "generationConfig": {
                "temperature": self.config.temperature,
                "maxOutputTokens": self.config.max_output_tokens,
                "responseMimeType": "application/json",
            },
        }
        url = self.config.provider_url.format(model=self.config.model_name)
        headers = {"Content-Type": "application/json", "x-goog-api-key": api_key}

        for attempt in range(self.config.retry_limit + 1):
            try:
                response = requests.post(
                    url,
                    headers=headers,
                    json=payload,
                    timeout=self.config.timeout_seconds,
                )
            except requests.Timeout as error:
                if attempt < self.config.retry_limit:
                    continue
                raise AIProviderTimeout("AI provider request timed out.") from error
            except requests.RequestException as error:
                raise AIProviderUnavailable("AI provider request failed.") from error

            if response.status_code == 429:
                if attempt < self.config.retry_limit:
                    continue
                raise AIProviderRateLimited("AI provider rate limit reached.")
            if response.status_code >= 500:
                if attempt < self.config.retry_limit:
                    continue
                raise AIProviderUnavailable("AI provider is temporarily unavailable.")
            if response.status_code < 200 or response.status_code >= 300:
                raise AIProviderUnavailable("AI provider rejected the request.")
            return self._parse_response(response)

        raise AIProviderUnavailable("AI provider request failed.")

    def _render_prompt(self, request: AIRequest) -> str:
        package = {
            "task": request.task.value,
            "structured_context": request.prompt.structured_context,
            "evidence_registry": [item.model_dump(mode="json") for item in request.prompt.evidence_registry],
            "knowledge_references": [item.model_dump(mode="json") for item in request.prompt.knowledge_references],
            "task_instructions": request.prompt.task_instructions,
            "output_schema": request.prompt.output_schema,
            "prompt_version": request.prompt.prompt_version,
        }
        return json.dumps(package, sort_keys=True, ensure_ascii=True, separators=(",", ":"))

    def _parse_response(self, response: Any) -> AIResponse:
        try:
            body = response.json()
            candidates = body.get("candidates") or []
            parts = ((candidates[0].get("content") or {}).get("parts") or [])
            text = next((part.get("text") for part in parts if isinstance(part, dict) and part.get("text")), "")
            if not isinstance(text, str) or not text.strip() or text.lstrip().startswith("```"):
                raise ValueError("response did not contain strict JSON text")
            decoded = json.loads(text)
            if not isinstance(decoded, dict):
                raise ValueError("response JSON must be an object")
            return AIResponse.model_validate(decoded)
        except Exception as error:
            if isinstance(error, AIProviderError):
                raise
            raise AIProviderInvalidResponse("AI provider returned malformed structured JSON.") from error


def build_configured_provider(config: AIProviderConfig | None = None) -> AIProvider:
    """Create a provider from config without importing provider details elsewhere."""

    config = config or load_ai_config()
    if not config.enabled:
        return NullAIProvider()
    if config.provider_name == "mock":
        return MockAIProvider(model=config.model_name)
    if config.provider_name == "gemini":
        if not os.getenv(config.api_key_env_var, "").strip():
            return NullAIProvider()
        return GeminiProvider(config)
    return NullAIProvider()


def normalize_provider_error(error: Exception) -> AIProviderError:
    """Convert an unexpected provider exception into a safe internal error."""
    if isinstance(error, AIProviderError):
        return error
    return AIProviderUnavailable("AI provider failed without a normalized error.")
